name: Daily Weather & Inference Pipeline

on:
  workflow_dispatch:
  schedule:
    # Run daily at 2 AM UTC
    - cron: '0 2 * * *'
  
jobs:
  run-daily-pipeline:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Install uv
      uses: astral-sh/setup-uv@v4
    
    - name: Set up Python
      run: uv python install 3.12
    
    - name: Install dependencies
      run: uv sync

    - name: Setup CDS API credentials  
      run: |
        echo "url: ${{ secrets.CDSAPI_URL }}" > $HOME/.cdsapirc
        echo "key: ${{ secrets.CDSAPI_KEY }}"


    - name: Run weather feature pipeline
      env:
        HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
      run: |
        cd notebooks
        pwd
        ls -la ../data/
        uv run ipython feature_pipeline_weather.ipynb
          
    - name: Run inference pipeline
      env:
        HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
      working-directory: notebooks
      run: |
        uv run ipython inference_pipeline.ipynb